import * as React from "react";
import PageLayout from "../components/PageLayout";
import Banner from "../components/Banner";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
import Favicon from "../assets/images/yext-favicon.ico";
 
 
 export const config: TemplateConfig = {
   name: "About",
 };
 
 
  export const getPath: GetPath<TemplateProps> = ({document}) => {
    return `about`;
 };
 
 export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
    relativePrefixToRoot,
    document
  }): HeadConfig => {
  return {
    title: "About Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
      {
        type: "link",
        attributes: {
          rel: "icon",
          type: "image/x-icon",
          href: relativePrefixToRoot + Favicon,
        },
      }
    ],
  };
};

  const About: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {
  const {
    _site, 
  } = document;

   return (
    <>
      <PageLayout >
        <Banner name="About Page" />
        <div className="centered-container">
          <div className="section space-y-10 px-10 text-xl">
              <h1 className="text-center font-semibold">Welcome to Yext Pages!</h1>
              <div className="px-14 space-y-5">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
          </div>
        </div>
      </PageLayout>
    </>
   );
 };
 
 export default About;
 